version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: localbite-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - localbite-db:/var/lib/mysql

volumes:
  localbite-db: 